server:
  port: 8888

spring:
  application:
    name: config-service
  security:
    user:
      name: admin
      password: 12345
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EduardoAzaldegui/Banca-proyecto-final.git
          default-label: config-data
          search-paths: config-data
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
